# Site settings
title:       Jose Tavares
author:      Jose Tavares
description: "Full Stack Magician"
baseurl:     ""
url:         "http://www.yconoclast.pt"
excerpt_separator: <!--more-->

# Google analytics
google_analytics: UA-56447609-2

# Optional features
animated:           true
show_related_posts: true
show_social_icons:  true

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: yconoclast

# Social icons
stackoverflow_id:
google_plus_id:
linkedin_username: josetavares17
angellist_username:
bitcoin_url:
paypal_url:
flattr_button:
soundcloud:
lastfm:

# Post sharing icons
show_sharing_icons: true
share_text: 'Share this post'
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: true
share_linkedin: true
share_digg: false
share_tumblr: false
share_reddit: true
share_stumbleupon: false
share_hackernews: true

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     5
sass:
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate
