# Site settings
title:       Jose Tavares blog
email:       josetavares00@gmail.com
author:      Jose Tavares
description: "Frontend Samurai | Passionate Web Developer"
baseurl:     ""
url:         "http://yconoclast.github.io"
excerpt_separator: <!--more-->

# Google analytics
google_analytics: UA-56447609-2

# Optional features
animated:           true
show_related_posts: true
show_social_icons:  true

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: yconoclast

# Social icons
github_username: yconoclast
stackoverflow_id:
twitter_username: yconoclast
google_plus_id:
linkedin_username: josetavares17
angellist_username:
bitcoin_url:
paypal_url:
flattr_button:
facebook: josetavares17
soundcloud:
lastfm:

# Post sharing icons
show_sharing_icons: true
share_text: 'Share this post'
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: true
share_linkedin: true
share_digg: false
share_tumblr: true
share_reddit: true
share_stumbleupon: false
share_hackernews: false

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     4
sass:
  compressed: true
gems:
  - jekyll-sitemap
